#!/usr/bin/env python3
"""Compatibility Python installer for contextd's Claude adapter.

The shell installer is the canonical path. This Python entry keeps older
automation working while using the same ENGINE_ROOT / KNOWLEDGE_ROOT vocabulary
and writing canonical ~/.contextd/config.json.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional


def resolve_dir(raw: Optional[str], default: Path) -> Path:
    if not raw:
        return default.resolve()
    return Path(raw).expanduser().resolve()


def validate_engine_root(engine_root: Path) -> None:
    if not engine_root.is_dir():
        print(f"Error: ENGINE_ROOT does not exist: {engine_root}", file=sys.stderr)
        sys.exit(1)
    if not (engine_root / ".claude" / "commands").is_dir() or not (engine_root / "agents").is_dir():
        print(
            f"Error: {engine_root} is not a contextd engine repo "
            "(missing .claude/commands or agents).",
            file=sys.stderr,
        )
        sys.exit(1)


def validate_knowledge_root(knowledge_root: Path) -> None:
    if not knowledge_root.is_dir():
        print(f"Error: knowledge_root does not exist: {knowledge_root}", file=sys.stderr)
        sys.exit(1)
    if not (knowledge_root / "workspaces").is_dir():
        print(f"Error: knowledge_root must contain workspaces/: {knowledge_root}", file=sys.stderr)
        sys.exit(1)


def sync_file(src: Path, dst: Path, label: str, dry_run: bool) -> None:
    if not dst.exists():
        print(f"  [NEW]       {label}")
        if not dry_run:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
    elif not filecmp.cmp(src, dst, shallow=False):
        print(f"  [UPDATED]   {label}")
        if not dry_run:
            shutil.copy2(src, dst)
    else:
        print(f"  [UNCHANGED] {label}")


def sync_dir(src_dir: Path, dst_dir: Path, label: str, dry_run: bool) -> None:
    print(f"-- {label} -> {dst_dir}")
    if not dry_run:
        dst_dir.mkdir(parents=True, exist_ok=True)
    for src in sorted(src_dir.glob("*.md")):
        sync_file(src, dst_dir / src.name, src.name, dry_run)
    print()


def write_json_config(path: Path, payload: dict, root_key: str, force: bool, dry_run: bool) -> None:
    desired_root = payload[root_key]
    if not path.exists():
        print(f"  [NEW]       {path}")
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        return

    try:
        existing = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        existing = {}

    current_root = existing.get(root_key)
    if current_root == desired_root:
        print(f"  [UNCHANGED] {root_key} is already {desired_root}")
    elif force:
        print(f"  [FORCED]    overwrite {path}")
        if not dry_run:
            path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    else:
        print(f"  [CONFLICT]  {root_key} current: {current_root or '<empty>'}")
        print(f"              {root_key} new:     {desired_root}")
        print(f"              Re-run with --force to overwrite or edit {path}")


def write_global_configs(knowledge_root: Path, default_workspace: Optional[str],
                         force: bool, dry_run: bool) -> None:
    contextd_config = Path.home() / ".contextd" / "config.json"
    legacy_config = Path.home() / ".claude" / "wiki-global.json"
    root = knowledge_root.as_posix()

    print(f"-- Canonical config -> {contextd_config}")
    write_json_config(
        contextd_config,
        {
            "_comment": (
                "Generated by contextd/scripts/install-to-claude.py. "
                "knowledge_root is canonical; legacy wiki globals are compatibility adapters."
            ),
            "knowledge_root": root,
            "default_workspace": default_workspace,
        },
        "knowledge_root",
        force,
        dry_run,
    )

    print(f"-- Legacy config -> {legacy_config}")
    write_json_config(
        legacy_config,
        {
            "_comment": (
                "Compatibility adapter generated by contextd/scripts/install-to-claude.py. "
                "Canonical config lives at ~/.contextd/config.json."
            ),
            "wiki_root": root,
            "default_workspace": default_workspace,
        },
        "wiki_root",
        force,
        dry_run,
    )
    print()


def remove_legacy_adapters(global_commands: Path, global_agents: Path, dry_run: bool) -> None:
    legacy_commands = {
        "wiki-backup": "contextd-backup",
        "wiki-detect": "contextd-detect",
        "wiki-eval": "contextd-eval",
        "wiki-explain": "contextd-explain",
        "wiki-report": "contextd-report",
        "wiki-restore": "contextd-restore",
        "wiki-setup": "contextd-setup",
        "wiki-trace": "contextd-trace",
        "wiki-upgrade": "contextd-upgrade",
        "wiki-version": "contextd-version",
        "wiki-viz": "contextd-viz",
        "use-wiki": "use-contextd",
        "update-wiki": "update-contextd",
        "rebase-wiki": "rebase-contextd",
    }
    for legacy, new_name in legacy_commands.items():
        path = global_commands / f"{legacy}.md"
        if path.exists():
            print(f"  [REMOVED]   {legacy}.md (renamed -> {new_name}.md)")
            if not dry_run:
                path.unlink()

    for legacy in [
        "wiki-planner",
        "wiki-context-selector",
        "wiki-plan-reviewer",
        "wiki-curator",
        "wiki-reviewer",
        "contextd-plan-reviewer",
    ]:
        path = global_agents / f"{legacy}.md"
        if path.exists():
            print(f"  [REMOVED]   {legacy}.md")
            if not dry_run:
                path.unlink()


def print_mcp_config(engine_root: Path, client: str, knowledge_root: Path,
                     workspace: Optional[str]) -> int:
    args = [
        sys.executable,
        str(engine_root / "scripts" / "cli.py"),
        "mcp-config",
        "--client",
        client,
        "--knowledge-root",
        str(knowledge_root),
    ]
    if workspace:
        args.extend(["--workspace", workspace])
    return subprocess.call(args)


def main() -> None:
    parser = argparse.ArgumentParser(description="Install contextd Claude adapter files.")
    parser.add_argument("engine_root", nargs="?", default=None,
                        help="Path to contextd engine repo")
    parser.add_argument("--engine-root", dest="engine_root_flag", default=None,
                        help="Path to contextd engine repo")
    parser.add_argument("--knowledge-root", default=None,
                        help="Canonical root containing workspaces/")
    parser.add_argument("--knowledge-repo", default=None,
                        help="Compatibility alias for --knowledge-root")
    parser.add_argument("--default-workspace", default=None,
                        help="Write default_workspace in global config")
    parser.add_argument("--print-mcp-config", choices=["claude", "cursor", "codex", "all"],
                        default=None, help="Print MCP snippet and exit")
    parser.add_argument("--dry-run", action="store_true", help="Print actions without writing files")
    parser.add_argument("--force", action="store_true", help="Overwrite global configs on root conflict")
    args = parser.parse_args()

    if args.knowledge_repo and not args.knowledge_root:
        print(
            "Warning: --knowledge-repo is a compatibility alias. "
            "Use --knowledge-root for canonical installs.",
            file=sys.stderr,
        )
        args.knowledge_root = args.knowledge_repo

    default_engine_root = Path(__file__).resolve().parent.parent
    engine_root = resolve_dir(args.engine_root_flag or args.engine_root, default_engine_root)
    validate_engine_root(engine_root)

    knowledge_root = resolve_dir(args.knowledge_root, engine_root)
    validate_knowledge_root(knowledge_root)

    if args.print_mcp_config:
        sys.exit(print_mcp_config(
            engine_root,
            args.print_mcp_config,
            knowledge_root,
            args.default_workspace,
        ))

    global_claude = Path.home() / ".claude"
    global_commands = global_claude / "commands"
    global_agents = global_claude / "agents"

    print(f"Engine root:    {engine_root}")
    print(f"Knowledge root: {knowledge_root}")
    if args.default_workspace:
        print(f"Default workspace: {args.default_workspace}")
    if args.dry_run:
        print("Mode:           DRY RUN (no changes)")
    print()

    sync_dir(engine_root / ".claude" / "commands", global_commands, "Slash commands", args.dry_run)
    sync_dir(engine_root / ".claude" / "agents", global_agents, "Subagents", args.dry_run)
    remove_legacy_adapters(global_commands, global_agents, args.dry_run)
    write_global_configs(knowledge_root, args.default_workspace, args.force, args.dry_run)

    print("Done.")
    print("Try:")
    print("  cd /path/to/your/codebase")
    print("  /contextd-setup")
    print("  contextd resolve")


if __name__ == "__main__":
    main()
